# fly.toml app configuration file generated for rootstore on 2023-04-17T22:34:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rootstore"
primary_region = "iad"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
