# Generated by Django 4.2 on 2023-04-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("pem", models.CharField(max_length=16384)),
                ("common_name", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Root_Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("source", models.URLField(max_length=1000)),
                ("certificates", models.ManyToManyField(to="storeviewer.certificate")),
            ],
        ),
        migrations.AddField(
            model_name="certificate",
            name="stores",
            field=models.ManyToManyField(to="storeviewer.root_store"),
        ),
    ]
