# Generated by Django 4.2 on 2023-04-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("pem", models.CharField(max_length=16384)),
                ("common_name", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Root_Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("source", models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Store_Contents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                ("last_trusted", models.DateTimeField()),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeviewer.certificate",
                    ),
                ),
                (
                    "root_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storeviewer.root_store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="root_store",
            name="certificates",
            field=models.ManyToManyField(
                through="storeviewer.Store_Contents", to="storeviewer.certificate"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="stores",
            field=models.ManyToManyField(
                through="storeviewer.Store_Contents", to="storeviewer.root_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="store_contents",
            constraint=models.UniqueConstraint(
                fields=("certificate", "root_store"),
                name="unique_migration_host_combination",
            ),
        ),
    ]
