# Generated by Django 4.2 on 2023-05-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeviewer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store_contents",
            name="last_trusted",
            field=models.DateTimeField(null=True),
        ),
    ]
