# Generated by Django 4.2 on 2023-05-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeviewer", "0002_alter_store_contents_last_trusted"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="owner",
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
